name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  run-code:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: run code.c
      run: ls; gcc code.c -o code; ./code
